language: java
after_success:
    "curl --ftp-create-dirs -T ./target/fastsharing.war -u $FTP_USER:$FTP_PASSWORD ftp://waws-prod-blu-043.ftp.azurewebsites.windows.net/site/wwwroot/webapps/ROOT.war"  